# Generated by Django 3.1.2 on 2020-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage0', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage4', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage5', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage6', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage7', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage8', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('detailImage9', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.store')),
            ],
        ),
    ]
