# Generated by Django 3.1.2 on 2020-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailImage0',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage1',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage2',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage3',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage4',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage5',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage6',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage7',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage8',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailImage9',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.CharField>/'),
        ),
    ]
